### ISSUE TITLE
Training Issues 

### ISSUE THREAD

**Issue by abhigoku10** [HanGuangXin/ByteTrack_ReID#11]
@HanGuangXin  i was able to train the model in one system, when i shifted the system and try to set it up from beginnign i am facing issues with the data load ing , its not able to read the files from the dataset folder only , if i try to manually add it the self.nID is 0 any idea how to solve it and make the training setps much elaborate 

thanks in advance

**Comment by HanGuangXin** [comment]
@abhigoku10  Hi, there!
It works well on NVIDIA 2080Ti and Tesla V100.
If there are some problems, please **provide more information**.

**Comment by HanGuangXin** [comment]
BTW, if you are using other datasets, you should add the code to compute `total_ids` like `exps/example/mot/yolox_s_mot17_half.py`.

**Comment by yanghaibin-cool** [comment]
@HanGuangXin  My understanding is that the data set can only be calculated if it has the id label, so it should not be possible to mix the data set training like the original? Please point it out if I misunderstood, thanks.

**Comment by HanGuangXin** [comment]
I think **there is a misunderstanding.** 

Datasets without id annotations **can be** used for training, just set `track_id`  to -1 and ignore them when computing `id_loss`.

**Comment by yanghaibin-cool** [comment]
> I think **there is a misunderstanding.**
> 
> Datasets without id annotations **can be** used for training, just set `track_id` to -1 and ignore them when computing `id_loss`, just like JDE/FairMOT.

I see, thank you for your answer, I benefited a lot.
