### ISSUE TITLE
about reproducing 

### ISSUE THREAD

**Issue by Gaoxinyue423** [HanGuangXin/ByteTrack_ReID#12]
Can you provide a pre-trained model?
For example yolox_s_mot17_half/latest_ckpt.pth.tar.
Thank you very much!

**Comment by HanGuangXin** [comment]
I'm a little busy now, will do it in a few days.

And I think `latest_ckpt.pth.tar` is trained model,  not pre-trained model.

**Comment by Gaoxinyue423** [comment]
OK. It is indeed the trained model. Thank you!

**Comment by HanGuangXin** [comment]
@Gaoxinyue423 Updated trained model in README. You can download it yourself.

**Comment by Gaoxinyue423** [comment]
OK. Thank you very much!
