### ISSUE TITLE
reproducing with yolox_s_mot17_half.py

### ISSUE THREAD

**Issue by yanghaibin-cool** [HanGuangXin/ByteTrack_ReID#14]
@HanGuangXin 
Sorry to bother you again!
Hello! I have finished training with yolox_s_mot17_half(self.train_ann=train_half.json;self.val_ann=val_half.json).However,I didn't get the desired result(YOLOX_S with mAP 55.5, MOTA 71.8 and IDF1 73.8).
Below is the result of my training：
Bytetrack-Reid with train.py:
![image](https://user-images.githubusercontent.com/72022193/162733375-163d7732-bbd7-4307-883f-fa5529dde965.png)
Bytetrack-Reid with track.py:
COCO indicator：
![image](https://user-images.githubusercontent.com/72022193/162734324-23962d82-aaa8-480c-bfbb-8d3cc66463b9.png)
MOT indicator:
![image](https://user-images.githubusercontent.com/72022193/162734206-c156ddcd-cb75-4a07-a939-9542599ce19d.png)
Bytetrack with train.py:
![image](https://user-images.githubusercontent.com/72022193/162734728-93cff9ec-9fa7-42db-ab97-8ecceaf59597.png)
Bytetrack with track.py:
COCO indicator:
![image](https://user-images.githubusercontent.com/72022193/162734859-4164f186-3570-483a-9d10-216ff5bd8850.png)
MOT indicator:
![image](https://user-images.githubusercontent.com/72022193/162734934-cc6af28c-f5ff-4ac2-aeca-ac402814b771.png)
Why is the tracking effect worse after adding Reid? Where am I going wrong?
Looking forward to your reply.

**Comment by HanGuangXin** [comment]
Sorry, my apologize! There is a bug in loss computing. 
You can pull the latest commit and see if you can get reasonable results.

**Comment by yanghaibin-cool** [comment]
> Sorry, my apologize! There is a bug in loss computing. You can pull the latest commit and see if you can get reasonable results.

The problem has been solved.
Thank you very much for your prompt reply these two days.
This is very helpful for my next study,wish you a happy life.
