### ISSUE TITLE
Data Association

### ISSUE THREAD

**Issue by yanghaibin-cool** [HanGuangXin/ByteTrack_ReID#15]
@HanGuangXin  
Hello, sorry to bother you again！
When the data is associated, why should the high-scoring detection frame that does not match the trajectory for the first time (motion+reid) and the trajectory that does not match the high-scoring detection frame match again through IoU (motion)? What is the benefit of doing this?
Looking forward to your reply.

**Comment by HanGuangXin** [comment]
show me the code, please.



---Original---
From: "poplar ***@***.***&gt;
Date: Fri, Apr 15, 2022 11:45 AM
To: ***@***.***&gt;;
Cc: "Han ***@***.******@***.***&gt;;
Subject: [HanGuangXin/ByteTrack_ReID] Data Association (Issue #15)




 
@HanGuangXin
 Hello, sorry to bother you again！
 When the data is associated, why should the high-scoring detection frame that does not match the trajectory for the first time (motion+reid) and the trajectory that does not match the high-scoring detection frame match again through IoU (motion)? What is the benefit of doing this?
 Looking forward to your reply.

**Comment by yanghaibin-cool** [comment]
> show me the code, please.
> […](#)
> ---Original--- From: "poplar ***@***.***&gt; Date: Fri, Apr 15, 2022 11:45 AM To: ***@***.***&gt;; Cc: "Han ***@***.******@***.***&gt;; Subject: [HanGuangXin/ByteTrack_ReID] Data Association (Issue #15) @HanGuangXin Hello, sorry to bother you again！ When the data is associated, why should the high-scoring detection frame that does not match the trajectory for the first time (motion+reid) and the trajectory that does not match the high-scoring detection frame match again through IoU (motion)? What is the benefit of doing this? Looking forward to your reply. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

https://github.com/HanGuangXin/ByteTrack_ReID/blob/c3deeec0fbfe3d48d91f2616b8c112ab26bba1e1/yolox/tracker/byte_tracker_FairMOT.py#L262

**Comment by HanGuangXin** [comment]
Step 1 in `byte_tracker_FairMOT.py` **only** uses appearance for association, so step 2 is necessary.
If you do not understand, please **refer to FairMOT paper**.

**Comment by HanGuangXin** [comment]
If you are not familiar with classic algorithms in MOT like SORT/DeepSORT/JDE/FairMOT, I think it is **necessary for you to learn them first**!

If there is not other questions, I will close this issue.

**Comment by yanghaibin-cool** [comment]
> If you are not familiar with classic algorithms in MOT like SORT/DeepSORT/JDE/FairMOT, I think it is **necessary for you to learn them first**!
> 
> If there is not other questions, I will close this issue.

OK, thanks for the reply. Next, I will study the code carefully.

**Comment by 972821054** [comment]
@yanghaibin-cool 您好，请问您有没有对没有track_id的情况进行处理？麻烦您了！
![image](https://user-images.githubusercontent.com/83146207/190847810-8b5105c4-90bf-4807-a369-a41da418710b.png)
