### ISSUE TITLE
Pretrained Weights for Gdrive

### ISSUE THREAD

**Issue by oyku-s** [HanGuangXin/ByteTrack_ReID#17]
Hello! 
Thanks for this amazing work. Can you please share the pretrained model in gdrive as well?

**Comment by HanGuangXin** [comment]
Hi! Google drive may be a little tricky for me, I think One Drive will also do the job? It may take some time.

**Comment by oyku-s** [comment]
Thank you very much! 
May I also ask about the password for the baidu link?

Thank you very much for your help.

**Comment by HanGuangXin** [comment]
jc69

**Comment by HanGuangXin** [comment]
@abhigoku10 I will update it ASAP, but not now. I have other priors to finish. Sorry for the delay.

**Comment by HanGuangXin** [comment]
@abhigoku10 @oyku-s Hi, I'm wondering whether I can share the weight by e-mail if you have no access to Baidu Netdisk, which is more convenient for me. So you can give me your e-mail address if possible.

**Comment by abhigoku10** [comment]
@HanGuangXin  this is my mail id abhigoku10@gmail.com

**Comment by HanGuangXin** [comment]
https://1drv.ms/u/s!Ah_DaS8JQYSHlnPl4vhZvz10JTB4?e=jpehmF
