### ISSUE TITLE
请问一下如何运行（作者提供了权重文件）

### ISSUE THREAD

**Issue by yidimopozhibai** [HanGuangXin/ByteTrack_ReID#19]
![666](https://user-images.githubusercontent.com/81897860/167289691-996d675c-7e1d-4b52-bc71-1ec8e1006f02.png)
emmm，yolox的权重文件和fairmot的权重文件是一个吗？应该如何使用增加了reid模块的本项目呢。望解答

**Comment by yanghaibin-cool** [comment]
Not a weights file, their detectors are not the same. How to use reid, it is recommended to look at documents such as tracker, evaluator and track.

**Comment by HanGuangXin** [comment]
@yanghaibin-cool Thanks for the reply!
