### ISSUE TITLE
请问一下reid模块已经添加到ByteTrack里面了吗？

### ISSUE THREAD

**Issue by alexHxun** [HanGuangXin/ByteTrack_ReID#20]
我看到base_tracker.py文件中，def update函数中添加的Id_feature似乎并没有使用，这个文件是不是弃用了，使用base_tracker_FairMOT.py代替了？

demo_track.py有更新的计划吗？似乎只更新了一点

**Comment by yanghaibin-cool** [comment]
The reid module was added, but the author said that the accuracy of the label was problematic during training. Looking forward to the author's repair, if you want to use the reid module, modify here
https://github.com/HanGuangXin/ByteTrack_ReID/blob/f5b0dc6f79393735478994e20f695246992e65da/yolox/evaluators/mot_evaluator.py#L15
demo_track.py:The modification of imageflow_demo() can refer to image_demo().

**Comment by alexHxun** [comment]
> The reid module was added, but the author said that the accuracy of the label was problematic during training. Looking forward to the author's repair, if you want to use the reid module, modify here
> 
> https://github.com/HanGuangXin/ByteTrack_ReID/blob/f5b0dc6f79393735478994e20f695246992e65da/yolox/evaluators/mot_evaluator.py#L15
> 
> 
> demo_track.py:The modification of imageflow_demo() can refer to image_demo().

OK. THANKS!

**Comment by HanGuangXin** [comment]
@yanghaibin-cool Thanks for your reply, it is truly helpful.
