### ISSUE TITLE
Training model

### ISSUE THREAD

**Issue by Gaoxinyue423** [HanGuangXin/ByteTrack_ReID#21]
I admire your realization. Can you provide the completed hybrid training model with Re-ID?
Maybe not mot17_half training model, which is the training model used in mot17 test set.
Thank you very much!

**Comment by HanGuangXin** [comment]
Thanks, but sorry. This repository is much like a base reference or a prototype. So all of my limited sources has to be used for training other algorithms.

But I think all of the codes needed to train the model on larger datasets has already be released. Just follow JDE/FairMOT to build the dataset.

**Comment by Gaoxinyue423** [comment]
That's OK. Thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Han ***@***.***&gt;; 
发送时间: 2022年5月11日(星期三) 中午11:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HanGuangXin/ByteTrack_ReID] Training model (Issue #21)





 
谢谢，但很抱歉。  这个存储库很像基本引用或原型。  所以我所有有限的资源都必须用于训练其他算法。 
 
但我认为在更大的数据集上训练模型所需的所有代码都已经发布。  只需按照 JDE/FairMOT 构建数据集。 
 
— 
直接回复此邮件， 在 GitHub 上查看 ，或 退订 。 
您收到此消息是因为您编写了该主题。 消息ID： <HanGuangXin/ByteTrack_ReID/issues/21/1123134166 @ github 。 com&gt;
