### ISSUE TITLE
track_id bug with fp16

### ISSUE THREAD

**Issue by yanghaibin-cool** [HanGuangXin/ByteTrack_ReID#22]
Hi,here.When targets is converted to FP16, the track_id will lose the precision, resulting in wrong labels for reid.
How to separate track_id annotations from variable targets. And set targets to torch.float16as current code, but keep track_id to be torch.float32.I tried to modify it, but it didn't work.
Looking forward to your update on this bug.Thank you.

**Comment by HanGuangXin** [comment]
I have already made a PR to ByteTrack and it is merged to master branch. Have you check it already?

https://github.com/ifzhang/ByteTrack/pull/184#issue-1217307315
https://github.com/ifzhang/ByteTrack/issues/182#issue-1215799773

And yes, the PR I made doesn't include operations in `yolo_head.py`, where reid loss is computed.

**Comment by HanGuangXin** [comment]
The changes in `yolo_head.py` should be 4 lines, more or less. I just have no time to verify the results in current version.

**Comment by yanghaibin-cool** [comment]
> The changes in `yolo_head.py` should be 4 lines, more or less. I just have no time to verify the results in current version.

Thanks, I will try to modify the id_loss in yolo_head.py myself. Thanks again for open-sourcing this project, the combination of bytetrack_reid and other tracking strategies has been very helpful for my work.

**Comment by HanGuangXin** [comment]
Just like I mentioned in https://github.com/ifzhang/ByteTrack/pull/184: "Hi, I'm thinking about separate track_id annotations from variable targets. And set targets to torch.float16as current code, but keep track_id to be torch.float32."

So the only thing you should do is eparate track_id annotations from variable targets, then pass it to yolo head. I think it is just a matter of some function interfaces.

If you finish it, a PR is welcome.

**Comment by HanGuangXin** [comment]
Or I can update it when I got time.

**Comment by yanghaibin-cool** [comment]
> Or I can update it when I got time.

![image](https://user-images.githubusercontent.com/72022193/168476578-67d61ede-32c4-4aa3-85b7-3de6f20cef6c.png)
Could I change it like this directly? It can be trained like this, but I don't know if it's right or not.

**Comment by HanGuangXin** [comment]
Hi, I don't think cat 2 tensors with different `dtype` is a correct operation.
