### ISSUE TITLE
Where is reid association?

### ISSUE THREAD

**Issue by huanmx** [HanGuangXin/ByteTrack_ReID#24]
Hi!
Where is reid association in BYTE? It seems that the association strategy in yolox.tracker.byte_tracker.py is same as ByteTrack.

**Comment by HanGuangXin** [comment]
Use fairmot file, please.



---Original---
From: ***@***.***&gt;
Date: Wed, May 25, 2022 17:34 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [HanGuangXin/ByteTrack_ReID] Where is reid association? (Issue #24)




 
Hi!
 Where is reid association in BYTE? It seems that the association strategy in yolox.tracker.byte_tracker.py is same as ByteTrack.

**Comment by huanmx** [comment]
Thanks for your reply!
Does the performance with reid head trained and BYTE track strategy is better than without reid head trained and BYTE track strategy?

**Comment by HanGuangXin** [comment]
I have provided results in README, please check it first before asking me.

**Comment by chenzhutian** [comment]
I would suggest you to explicity list the results in a table and highlight how many points gain or loss after applying ReID to BYTE track, so that folks wont keep asking and you dont need to keep saying "read this first"

**Comment by chenzhutian** [comment]
And you will get stars more and faster
