### ISSUE TITLE
loss_ id is Nan

### ISSUE THREAD

**Issue by yangwhf** [HanGuangXin/ByteTrack_ReID#25]
loss_ id and total_ loss sometimes becomes Nan. I'm not sure if this is normal
![b6473bba5a103a324fbae6212be8d6e](https://user-images.githubusercontent.com/25499076/173484841-90dcd050-fc32-4c33-8d19-eee2a90ce291.png)

**Comment by HanGuangXin** [comment]
Provide more information, please.



---Original---
From: ***@***.***&gt;
Date: Tue, Jun 14, 2022 11:09 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [HanGuangXin/ByteTrack_ReID] loss_ id is Nan (Issue #25)




 
loss_ id and total_ loss sometimes becomes Nan. I'm not sure if this is normal

**Comment by yangwhf** [comment]
> 请提供更多信息。
> […](#)
> ---原创---来自：***@***.***> 日期：2022 年 6 月 14 日星期二上午 11:09 至：***@***.***>; 抄送：***@***.***>; 主题：[汉光新/ByteTrack_ReID] loss_id is Nan（问题#25）loss_id和total_loss有时会变成Nan。我不确定这是否正常 — 直接回复此电子邮件、在 GitHub 上查看或取消订阅。您收到此消息是因为您订阅了此线程。消息 ID：***@***.***>

Use "MOT17 half train" and "CrowdHuman" mixed dataset training, use "exps/example/mot/yolox_x_ablation.py" and modified according to "exps/example/mot/yolox_s_mot17_half.py"

**Comment by HanGuangXin** [comment]
It is normal when you training with mixed MOT datasets and detection datasets. 

If you do not want it happen, maybe try larger batchsize.

**Comment by yangwhf** [comment]
> 当您使用混合的 MOT 数据集和检测数据集进行训练时，这是正常的。
> 
> 如果您不希望它发生，可以尝试更大的批量。

Thanks for your answer, I'm confused why this is happening?

**Comment by HanGuangXin** [comment]
Detection datasets do not has ID annotations. That's all.

**Comment by yangwhf** [comment]
> 检测数据集没有 ID 注释。就这样。

I see, thank you for your answer

**Comment by HanGuangXin** [comment]
:-)
