### ISSUE TITLE
How to track with FairMOT

### ISSUE THREAD

**Issue by mtmyyy** [HanGuangXin/ByteTrack_ReID#28]
I tried to use fairmot in`fairmot_tracker.py` for tracking, but I got an error message`ValueError: too many values to unpack (expected 2)`,  the input was incorrect when using the `upadte` function, but I carefully checked that the input met the requirements
```
    online_targets, lost_t = tracker.update(outputs[0], info_imgs_, self.img_size, id_feature)   # TODO: ReID. add 'id_feature'
                             │       │      │           │           │    │         └ tensor([[ 1.9701e-01,  2.9549e-02, -1.4506e-02, -1.1046e-02, -3.5317e-02,
                             │       │      │           │           │    │                     4.8791e-02,  3.2311e-01,  1.2805e-01, -1....
                             │       │      │           │           │    └ (896, 1600)
                             │       │      │           │           └ <yolox.evaluators.mot_evaluator.MOTEvaluator object at 0x7f5ec0ea7f70>
                             │       │      │           └ [1080, 1920, 1, 1, '02/img1/000001.jpg']
                             │       │      └ [tensor([[ 6.3289e+01,  8.5052e+01,  1.2288e+02,  1.6780e+02,  9.9645e-01,
                             │       │                  9.0823e-01,  0.0000e+00,  1.4871e+00,  2...
                             │       └ <function FairMOTTracker.update at 0x7f5ec2d6c280>
                             └ <yolox.tracker.byte_tracker_FairMOT.FairMOTTracker object at 0x7f60b4757af0>

ValueError: too many values to unpack (expected 2)
```

**Comment by HanGuangXin** [comment]
Sorry for being late. Could you tell me which line this is and which command do you use?

**Comment by mtmyyy** [comment]
`yolox/evaluators/mot_evaluator.py line 355`
with the tracker `yolox/tracker/fairmot_tracker.py` fairmot
And I just changed `bytetracker` to Fairmot `tracker = FairMOTTracker(self.args)`

The command is just a simple execution of track.py without big change
Why is there an issue with the input of the `update` function and i can run `track.py` with ByteTracker successly without this issue

**Comment by mtmyyy** [comment]
Oh, I made a very low-level mistake，thank you very much
