### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by YmanChris** [HanGuangXin/ByteTrack_ReID#3]
您好，问个问题，执行python3 tools/train.py -f exps/example/mot/yolox_x_ablation.py -d 3 -b 4 --fp16 -o -c pretrained/yolox_x.pth和ByteTrack运行指令一样，ByteTrack运行正常，在ByteTrack_ReID运行报错，有重新执行setup，请问这个版本的代码是可正常执行的吗？
![image](https://user-images.githubusercontent.com/18142592/151307789-f28c4465-ca51-4961-99fc-89bf666c27bb.png)

**Comment by HanGuangXin** [comment]
Of course it works.
You should modify the code of `demo_track.py` w.r.t `track.py`, if you need do the visualization.
And I will update it as soon as possible.
@YmanChris

**Comment by YmanChris** [comment]
> Of course it works. You should modify the code of `demo_track.py` w.r.t `track.py`, if you need do the visualization. And I will update it as soon as possible. @YmanChris

Thank you for your response. And I have another question. My computer server is 2080ti with 11g gpu memory. Is it enough to run this project. It reports error about cuda out of memory. 
Wish your reply.

**Comment by HanGuangXin** [comment]
Setting batchsize to smaller value will handle it. @YmanChris
