### ISSUE TITLE
Pretrained Model 

### ISSUE THREAD

**Issue by abhigoku10** [HanGuangXin/ByteTrack_ReID#4]
@HanGuangXin  thanks for your work and sharing it to opensource 
1. Can you please share the pretrained model for person reid ?
2. Is there inference pipeline to check the shared pre trained model 
3. Can we extend this work for vehicle reid also ? if so what all changes have to be made to the current source code 

Thanks in advance

**Comment by HanGuangXin** [comment]
@abhigoku10 
1. Trained model will be updated soon, or you can train it yourself.
2. `track.py` will do the job.
3. Yes, and I don't think there is any code to be modified.

**Comment by abhigoku10** [comment]
@HanGuangXin  thanks for the response 
3. so if vehicle reid should be trained then our data should consisits fo reid info ? so are you aware of the dataset for vehicle reid

**Comment by HanGuangXin** [comment]
> @HanGuangXin thanks for the response 3. so if vehicle reid should be trained then our data should consisits fo reid info ? so are you aware of the dataset for vehicle reid

Training of ReID need ID annots. VeRi and VehicleID are benchmarks for vehicle ReID task.
