### ISSUE TITLE
Training Error 

### ISSUE THREAD

**Issue by abhigoku10** [HanGuangXin/ByteTrack_ReID#5]
@HanGuangXin  hi htnaks for sharing your codebase i am having issues while training on MOT17 and MOT20 below is the error "
Traceback (most recent call last):

File "tools/train.py", line 122, in <module>
args=(exp, args),
│ └ Namespace(batch_size=1, ckpt='pretrained/yolox_x.pth', devices=0, dist_backend='nccl', dist_url=None, exp_file='exps/example/...
└ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...

> File "/home/anaconda3/envs/p37/lib/python3.7/site-packages/yolox-0.1.0-py3.7-linux-x86_64.egg/yolox/core/launch.py", line 90, in launch
main_func(*args)
│ └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
└ <function main at 0x7fad0f52cae8>

File "tools/train.py", line 100, in main
trainer.train()
│ └ <function Trainer.train at 0x7fad0f566ea0>
└ <yolox.core.trainer.Trainer object at 0x7fad0f488400>

File "/home/anaconda3/envs/p37/lib/python3.7/site-packages/yolox-0.1.0-py3.7-linux-x86_64.egg/yolox/core/trainer.py", line 77, in train
self.train_in_epoch()
│ └ <function Trainer.train_in_epoch at 0x7fad0f56ed90>
└ <yolox.core.trainer.Trainer object at 0x7fad0f488400>
File "/home/anaconda3/envs/p37/lib/python3.7/site-packages/yolox-0.1.0-py3.7-linux-x86_64.egg/yolox/core/trainer.py", line 86, in train_in_epoch
self.train_in_iter()
│ └ <function Trainer.train_in_iter at 0x7fad0f56e840>
└ <yolox.core.trainer.Trainer object at 0x7fad0f488400>
File "/home/anaconda3/envs/p37/lib/python3.7/site-packages/yolox-0.1.0-py3.7-linux-x86_64.egg/yolox/core/trainer.py", line 92, in train_in_iter
self.train_one_iter()
│ └ <function Trainer.train_one_iter at 0x7fad0f509510>
└ <yolox.core.trainer.Trainer object at 0x7fad0f488400>
File "/home/anaconda3/envs/p37/lib/python3.7/site-packages/yolox-0.1.0-py3.7-linux-x86_64.egg/yolox/core/trainer.py", line 112, in train_one_iter
self.scaler.scale(loss).backward() # loss.backward
│ │ │ └ <unprintable Tensor object>
│ │ └ <function GradScaler.scale at 0x7fad245a4b70>
│ └ <torch.cuda.amp.grad_scaler.GradScaler object at 0x7fad0f488048>
└ <yolox.core.trainer.Trainer object at 0x7fad0f488400>
File "/home/anaconda3/envs/p37/lib/python3.7/site-packages/torch/_tensor.py", line 307, in backward
torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
│ │ │ │ │ │ │ └ None
│ │ │ │ │ │ └ False
│ │ │ │ │ └ None
│ │ │ │ └ None
│ │ │ └ <unprintable Tensor object>
│ │ └ <function backward at 0x7fad2425c0d0>
│ └ <module 'torch.autograd' from '/home/anaconda3/envs/p37/lib/python3.7/site-packages/torch/autograd/__init__.py'>
└ <module 'torch' from '/home/anaconda3/envs/p37/lib/python3.7/site-packages/torch/__init__.py'>
File "/anaconda3/envs/p37/lib/python3.7/site-packages/torch/autograd/__init__.py", line 156, in backward
allow_unreachable=True, accumulate_grad=True) # allow_unreachable flag

RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1."

THanks in adavance

**Comment by HanGuangXin** [comment]
I have no idea for now. Did you successfully finish training on **origin ByteTrack**?

**Comment by HanGuangXin** [comment]
Did you modified the some codes?

**Comment by HanGuangXin** [comment]
`Assertion t >= 0 && t < n_classes failed.` is the core error.

So check classes of Detection or ReID for the dataset.
@abhigoku10

**Comment by abhigoku10** [comment]
@HanGuangXin  hi thanks for the suggestion but when i mix the mot17 and mot20 dataset and try to train i get the following error 

python tools/train.py -f exps/example/mot/yolox_x_mix_mot20_ch.py -d 1 -b 1 --fp16 -o -c pretrained/yolox_x.pth

Training of experiment is done and the best AP is 0.00
/pytorch/aten/src/ATen/native/cuda/[Loss.cu:247](http://loss.cu:247/): nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [2,0,0] Assertion t >= 0 && t < n_classes failed.
/pytorch/aten/src/ATen/native/cuda/[Loss.cu:247](http://loss.cu:247/): nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [3,0,0] Assertion t >= 0 && t < n_classes failed.
/pytorch/aten/src/ATen/native/cuda/[Loss.cu:247](http://loss.cu:247/): nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [4,0,0] Assertion t >= 0 && t < n_classes failed.
/pytorch/aten/src/ATen/native/cuda/[Loss.cu:247](http://loss.cu:247/): nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [21,0,0] Assertion t >= 0 && t < n_classes failed.
2022-05-05 19:05:59 | ERROR    | yolox.core.launch:90 - An error has been caught in function 'launch', process 'MainProcess' (2047981), thread 'MainThread' (139941941454016):

**Comment by HanGuangXin** [comment]
Hi, my suggestion is also the same. And I am a little busy right now, having no time to debug for you.

`Assertion t >= 0 && t < n_classes failed.` is the core error.

So check classes of Detection or ReID for the dataset.

Besides, you can check README updated recently. This error maybe is related to that bug.

Or, just google it.
