### ISSUE TITLE
What metrics are the ones in the second list

### ISSUE THREAD

**Issue by andrybicio** [HanGuangXin/ByteTrack_ReID#6]
After having trained the yolox-s network on half mot17, I run the local evaluation with:
`python3 tools/track.py -f exps/example/mot/yolox_s_mot17_half.py -c YOLOX_outputs/id_loss_1.0/best_ckpt.pth.tar -b 1 -d 2 --fp16 --fuse`

Finally obtaining the following results
![metrics](https://user-images.githubusercontent.com/56033694/154951757-c4c5b769-d267-43c6-a3e2-20244f619d8c.png)

Though I do not understand the second set of values, especially the columns  IDt, IDa, IDm. I tried also to check [motmetrics library](https://github.com/cheind/py-motmetrics), but did not find any helpful result.

**Comment by HanGuangXin** [comment]
@andrybicio Sorry about the late reply! Actually I do not know the meaning of IDt, IDa, IDm, either.

But the metrics are from origin bytetrack, you may bring an issue in ByteTrack?

BTW, the most useful metrics are HOTA, MOTA, IDF1, so I don't think IDt, IDa, IDm matter a lot.

**Comment by HanGuangXin** [comment]
I'm closing this issue. If you have other questions, please open another one.
