### ISSUE TITLE
Code understanding 

### ISSUE THREAD

**Issue by abhigoku10** [HanGuangXin/ByteTrack_ReID#7]
@HanGuangXin  thanks for sharing hte code base , i having the following queries 

1. I was able to train only on MOT17 data , can we scale the training to other datasets similar to Bytetrack 
2. From the code structure perspective i am to see that you have added any additional reid head to the yolox architecture and this embedding from the reid ur passing it to the tracker, am i right in understanding ? if so by training with larger datasets can we use this model for multicamera person reidentification?
3. In your comments you have mentioned "#TODO Reid" does that mean you have already implemented it and using these heads in the inference 

Thanks in adavance

**Comment by HanGuangXin** [comment]
@abhigoku10 Sorry for the late reply!

1. Of course yes. But there may be some data format issues to do, which is normal.
2. A ReID-head? Yes! Use ReID datasets? I don't think so. The training should be done with the whole image, not cropped boxes.
3. 'TODO' just means highlight, which does not mean real 'TODO'.

**Comment by HanGuangXin** [comment]
I'm closing this issue. If you have other questions, please open another one.
